version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    volumes:
      - "./data/redis:/data"
    expose:
      - 6379

  yolo_segment:
    container_name: yolo_segment
    build: .
    environment:
      - TYPE_ENV=SEGMENT
      - MODEL_DIR=/data/models
      - RQ_QUEUE_NAME=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AIXBLOCK_USE_REDIS=false
      - HOST_NAME=https://dev-us-west-1.aixblock.io
    ports:
      - 9090:9090
      - 6006:6006
      - 12345:12345
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - "./data/server:/data"
      - "./logs:/app/logs"

  yolo_detect:
    container_name: yolo_detect
    build: .
    environment:
      - TYPE_ENV=DETECT
      - MODEL_DIR=/data/models
      - RQ_QUEUE_NAME=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AIXBLOCK_USE_REDIS=false
      - HOST_NAME=https://dev-us-west-1.aixblock.io
    ports:
      - 9091:9090 
      - 6007:6006 
      - 12346:12345
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - "./data/server:/data"
      - "./logs:/app/logs"
